version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user

hooks:
  ApplicationStop:
   - location: scripts/beforeInstall.sh
     timeout: 300
     runas: ec2-user
  AfterInstall:
   - location: scripts/afterInstall.sh
     timeout: 300
     runas: ec2-user
  ApplicationStart:
   - location: scripts/applicationStart.sh
     timeout: 300
     runas: ec2-user